# Cloudflare Pages Configuration
name = "linda-osunga-virtual-care"
compatibility_date = "2024-06-15"

# Pages configuration
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[env.production]
NODE_VERSION = "18"
NPM_VERSION = "latest"
